# Generated by Django 5.0.6 on 2024-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_useremployee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='isAdmin',
            field=models.BooleanField(help_text='is admin'),
        ),
    ]
