# Generated by Django 5.0.6 on 2024-05-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_employee_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='db_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.useremployee'),
        ),
    ]
