# Generated by Django 5.0.6 on 2024-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_employee_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
